version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: querybuilder
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always
  
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-frontend
  #   ports:
  #     - 3050:3000
  #   restart: always
  #   depends_on:
  #     - api
